=== gauravdave083/XML-Basics-Assignment/Training_Bootcamp/Bank.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="bank">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="account" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="holder">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="firstName" type="xs:string"/>
                    <xs:element name="lastName" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="accountType" type="xs:string"/>
              <xs:element name="balance" type="xs:decimal"/>
              <xs:element name="transactions">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="transaction" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="txnId" type="xs:string"/>
                          <xs:element name="type" type="xs:string"/>
                          <xs:element name="amount" type="xs:decimal"/>
                          <xs:element name="date" type="xs:date"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== gauravdave083/XML-Basics-Assignment/Training_Bootcamp/Bank.xml
<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Bank.xsd">
  <account id="A123">
    <holder>
      <firstName>Ravi</firstName>
      <lastName>Verma</lastName>
    </holder>
    <accountType>Savings</accountType>
    <balance>10000.50</balance>
    <transactions>
      <transaction>
        <txnId>T001</txnId>
        <type>Credit</type>
        <amount>5000.00</amount>
        <date>2025-07-01</date>
      </transaction>
      <transaction>
        <txnId>T002</txnId>
        <type>Debit</type>
        <amount>1000.00</amount>
        <date>2025-07-05</date>
      </transaction>
    </transactions>
  </account>
</bank>
